const c_Pictures = [
    "/assets/pictures/Wet-Leg_Alice-Backham.avif",
    "/assets/pictures/Wet-Leg_Alternate.jpg",
    "/assets/pictures/Wet-Leg_Camping.jpg",
    "/assets/pictures/Wet-Leg_Cofee.jpg",
    "/assets/pictures/Wet-Leg_concert.jpg",
    "/assets/pictures/Wet-Leg_Doors.jpg",
    "/assets/pictures/Wet-Leg_FamilyPictures.png",
    "/assets/pictures/Wet-Leg_Forest.jpg",
    "/assets/pictures/Wet-Leg_Fuck.jpg",
    "/assets/pictures/Wet-Leg_Goth.jpg",
    "/assets/pictures/Wet-Leg_Guitar.jpg",
    "/assets/pictures/Wet-Leg_ketchup.jpg",
    "/assets/pictures/Wet-Leg_LookMyEyes.jpg",
    "/assets/pictures/Wet-Leg_Metal.jpg",
    "/assets/pictures/Wet-Leg_moto.jpg",
    "/assets/pictures/Wet-Leg_Muscles.jpg",
    "/assets/pictures/Wet-Leg_Nashville.jpg",
    "/assets/pictures/Wet-Leg_Old-pictures.jpg",
    "/assets/pictures/Wet-Leg_Room.jpg",
    "/assets/pictures/Wet-Leg_Seaboat.jpg",
    "/assets/pictures/Wet-Leg_Sky.jpg",
    "/assets/pictures/Wet-Leg_Smile.jpg",
    "/assets/pictures/Wet-Leg_Spin.jpg",
    "/assets/pictures/Wet-Leg_Stairs.jpg",
    "/assets/pictures/Wet-Leg_Sunglasses.jpg",
    "/assets/pictures/Wet-Leg_Worms.jpg",
    "/assets/pictures/Wet-Leg_Jump.jpg",
    "/assets/pictures/Wet-Leg_PRESS.jpg",
    "/assets/pictures/Wet-Leg_WeirdDreams.jpg",
    // "/assets/pictures/Wet-Leg_.jpg",
];

export default c_Pictures;